name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      MAINLINE: refs/heads/master
      DOCKERTAG: latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      # This also runs nix-build.
      - uses: cachix/cachix-action@v8
        with:
          name: srid
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # Only needed for private caches
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # This downloads deps from Nix cache, builds neuron, as well as run tests
      - name: Build ðŸ”§
        run: |
          nix-build -j4 --no-out-link ci.nix
          # Test default.nix
          nix-build -j4
          # Test flake.nix
          nix build --out-link flake-result
      - name: Verify output of default.nix & flake.nix
        run: |
          [ $(readlink result) = $(readlink flake-result) ]
      - name: Retrieve neuron version
        run: |
          echo "NEURONVER=$(./result/bin/neuron --version)" >> $GITHUB_ENV
      - name: Publish Docker image to Docker Hub
        if: ${{ github.ref == env.MAINLINE && runner.os == 'Linux' }}
        run: |
          docker load -i $(nix-build docker.nix --argstr tag "${{ env.DOCKERTAG }}")
          docker tag "sridca/neuron:${{ env.DOCKERTAG }}" "sridca/neuron:${{env.NEURONVER}}"
          echo ${{ secrets.DOCKER_PASS }} | docker login -u sridca --password-stdin
          set -x
          docker push "sridca/neuron:${{ env.DOCKERTAG }}"
          docker push "sridca/neuron:${{ env.NEURONVER }}"
